/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Fri Apr 11 21:31:07 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void mouse_Outputs_wrapper(real_T *SCALED_X,
                          real_T *SCALED_Y,
                          real_T *CLEAR)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
#ifndef MATLAB_MEX_FILE

	read(i,buffer,3);

    CLEAR[0]=0;
    
		if(buffer[0]==10)
        {
		printf("RIGHT CLICK\n");
        CLEAR[0]=1;   
        }
		RELATIVE_X+=buffer[1];
		RELATIVE_Y+=buffer[2];
	
			if(RELATIVE_X>MAX_POS_X) 
			RELATIVE_X=MAX_POS_X;
			else if(RELATIVE_X < -MAX_POS_X )
			RELATIVE_X=-MAX_POS_X;

			if(RELATIVE_Y>MAX_POS_Y) 
			RELATIVE_Y=MAX_POS_Y;
			else if(RELATIVE_Y<-MAX_POS_Y)
			RELATIVE_Y=-MAX_POS_Y;

		SCALED_X[0]=RELATIVE_X/MAX_POS_X*X_SCALE_LIMIT;
		SCALED_Y[0]=RELATIVE_Y/MAX_POS_Y*Y_SCALE_LIMIT;

		printf("[%f,%f]\n",SCALED_X[0],SCALED_Y[0]);



#endif
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
